#!/bin/sh
# Helper script to download and build all EPICS dependencies

# Environment
# EPICS_VERSIONS    space separated list of EPICS Base versions
# WORKDIR           build directory
# USE_CRYPTO        YES/NO : includes OPC UA Security support

PVA_MODS="normativeTypes pvAccess pvData pvDatabase pva2pva pvaClient"

for v in ${EPICS_VERSIONS}; do
    mkdir ${WORKDIR}/${v}
    cd ${WORKDIR}/${v}
    echo
    echo Building EPICS Base ${v} and gtest support module
    echo

    # Create RELEASE.local and CONFIG_SITE.local
    printf "GTEST=${WORKDIR}/${v}/gtest\nOPCUA=${WORKDIR}/${v}/opcua\nEPICS_BASE=${WORKDIR}/${v}/base\n" > RELEASE.local
    envsubst > CONFIG_SITE.local << 'END'
# Path to the Unified Automation OPC UA C++ SDK
UASDK = ${WORKDIR}/sdk

# How the Unified Automation SDK shared libraries are deployed
#   SYSTEM = shared libs are in a system location
#   PROVIDED = shared libs are in $(UASDK_SHRLIB_DIR)
#   INSTALL = shared libs are installed (copied) into this module
#   EMBED = link SDK code statically into libopcua,
#           SDK libraries are not required on target system
UASDK_DEPLOY_MODE = EMBED
UASDK_LIB_DIR = $(UASDK)/lib
UASDK_SHRLIB_DIR = $(UASDK_LIB_DIR)
# How the Unified Automation SDK libraries were built
UASDK_USE_CRYPTO = ${USE_CRYPTO}
UASDK_USE_XMLPARSER = YES
END
    echo RELEASE.local:
    cat RELEASE.local
    echo CONFIG_SITE.local:
    cat CONFIG_SITE.local
    echo

    # EPICS Base
    curl -L https://epics-controls.org/download/base/base-${v}.tar.gz | tar xzf -
    mv base-${v} base
    # Do not build PVA related modules
    if [ -d base/modules ]; then
        for mod in ${PVA_MODS}; do
            mv base/modules/${mod}/Makefile base/modules/${mod}/Makefile-do-not-build
        done
    fi
    echo "USR_CXXFLAGS_Linux += -std=c++11" > base/configure/CONFIG_SITE.local
    make -j2 -s -C base
    make -j2 -s -C base clean

    # Module gtest
    curl -L https://github.com/epics-modules/gtest/archive/refs/tags/v1.0.1.tar.gz | tar xzf -
    mv gtest-1.0.1 gtest
    make -j2 -s -C gtest
    make -j2 -s -C gtest clean
done
